version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: shortlink-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: shortlink_pro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shortlink-network

  redis:
    image: redis:7-alpine
    container_name: shortlink-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shortlink-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shortlink-backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/shortlink_pro
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - backend_logs:/app/src/logs
    networks:
      - shortlink-network

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shortlink-worker
    restart: unless-stopped
    command: node src/jobs/worker.js
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/shortlink_pro
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - shortlink-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shortlink-frontend
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - shortlink-network

networks:
  shortlink-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
  backend_logs:
